#!/bin/bash
# Path to the manifest generated by Tauri
MANIFEST="src-tauri/gen/android/app/src/main/AndroidManifest.xml"
PERM='<uses-permission android:name="android.permission.RECORD_AUDIO" />'

if [ -f "$MANIFEST" ]; then
    echo "Injecting permissions into $MANIFEST..."
    sed -i "/<application/i $PERM" "$MANIFEST"
else
    echo "Manifest not found!"
    exit 1
fi
